# Generated by Django 4.1.3 on 2022-11-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YeniResim",
        ),
    ]
